### ISSUE TITLE
Please update futures-rs to 0.3.1

### ISSUE THREAD

**Issue by Silentdoer** [actix/actix#298] opened 2019-11-25 09:25 UTC
Hi, please update futures to 0.3.1

**Comment by Luminoth** [comment] 2019-11-26 17:29
It would be great if an update to tokio 0.2 could come along with this

**Comment by fafhrd91** [comment] 2019-11-26 19:27
tokio team did nice thing, actix now is not compatible with tokio anymore

**Comment by cdbattags** [comment] 2019-11-26 19:39
@fafhrd91 what?! How so?!

**Comment by cdbattags** [comment] 2019-11-26 19:42
This framework is one of the biggest built on top of tokio so I think we'd have some weight for asking for backwards compatibility of a certain form.

What changed in last few days?

**Comment by fafhrd91** [comment] 2019-11-26 19:44
You can not spawn !Send futures anymore. I am planing to add custom runtime and drop tokio dependency

**Comment by cdbattags** [comment] 2019-11-26 19:54
So something specific in the executor? Any idea why this new design decision?

Wouldn't building a runtime for actix be quite a huge feat? Why not just fork and add feature to tokio worst case?

**Comment by fafhrd91** [comment] 2019-11-26 19:57
Actix is single threaded, tokio mostly multithreaded. Actix does not need any complexity

**Comment by asonix** [comment] 2019-11-26 20:18
There exists work to provide support for !Send futures in tokio: https://github.com/tokio-rs/tokio/pull/1733

Rather than introduce an additional asynchronous runtime (we already have tokio and async-std) it might be worth waiting for tokio to again support !Send

**Comment by fafhrd91** [comment] 2019-11-26 20:21
actix uses maybe 10-15% of tokio, I am not sure why I need other 85% all the time.

**Comment by fafhrd91** [comment] 2019-11-26 20:22
But obviously, modularity is not a concern anymore.

**Comment by cdbattags** [comment] 2019-11-26 20:40
Async-std works currently? That's news to me. Where can I find the different runtime "modules" source code? And any instructions for implementing a new one?

Which actix repos/folders to dig into?

**Comment by asonix** [comment] 2019-11-26 21:01
@cdbattags I wasn't trying to imply that actix works on top of async-std or tokio 0.2, I was just stating that these options exist as asynchronous runtimes, and I didn't think introducing a third asynchronous runtime was a good idea.

**Comment by cdbattags** [comment] 2019-11-26 21:03
Ahhh @asonix you were just referring to there existing multiple runtimes for futures in the Rust eco right now?

@fafhrd91 the way I look at it is that the 85% we don't use slows crate/package download time and compile time but that's about it, no?

If we need to reduce binary size later we can approach a new runtime then, no?

And why is modularity "not a concern anymore"?

**Comment by hawkw** [comment] 2019-11-26 22:33
FWIW, in the new `tokio` 0.2 release, it should be much easier for crates like Actix to opt in only to the features they use, via feature flags: https://github.com/tokio-rs/tokio/pull/1811

This was intended primarily for libraries which need only some features from `tokio` but don't want to burden their users with longer compile times. :)

**Comment by fafhrd91** [comment] 2019-11-27 00:30
At the moment we are evaluating option to drop tokio completely

**Comment by krircc** [comment] 2019-11-27 00:37
@cdbattags Current async-std also can not spawn !Send futures

**Comment by hawkw** [comment] 2019-11-27 01:13
FWIW, the current `master` version of `tokio` [now has an API for spawning `!Send` futures](https://github.com/tokio-rs/tokio/commit/38e602f4d812c196d5dc0bc245e79ccad4e77cfd), and it should be released in the near future. Hopefully this helps!

**Comment by Extrawurst** [comment] 2019-11-27 08:36
and its released: https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.1

**Comment by cdbattags** [comment] 2019-11-28 00:01
> and its released: https://github.com/tokio-rs/tokio/releases/tag/tokio-0.2.1

Thoughts, @fafhrd91?

**Comment by kanekv** [comment] 2019-12-01 10:35
Btw, if actix moves away from tokio it will be painful to use other crates that require tokio runtime (tonic, hyper, etc)?

**Comment by carllerche** [comment] 2019-12-03 22:01
@fafhrd91 It's unfortunate to hear, I would be eager to talk out the points in 0.2 that don't work for you. I had reached out to you in the past to ask for early feedback to make sure the changes worked for Actix, but unfortunately you did not have any availability. We did our best to ensure that the Actix case was covered.

> But obviously, modularity is not a concern anymore.

Modularity is a big concern. Using feature flags, we can reduce the total amount of code while providing greater flexibility (mixing feature flags cross crates did not work very well). You can still only enable the components that you need. If there is something more specific, I would love to hear it.

> You can not spawn `!Send` futures anymore. 

As mentioned by others, this is now supported. The very initial release of 0.2 shipped without `task::LocalSet`, but mostly to get something out the door as `task::LocalSet` is forwards compatible. I would say that being able to fully decouple the concern of scheduling `!Send` tasks from the concern of I/O shows greater modularity?

Anyway, if you have specific issues you wish to discuss, please ping me or open an issue on the Tokio repo and I would be happy to work through them.

**Comment by fafhrd91** [comment] 2019-12-04 02:44
My initial thoughts was related to 0.2.0 release. I think LocalSet should work.

Closing ticket as path for actix actors to async/await is not clear yet

**Closed by fafhrd91** 2019-12-04 02:44 UTC

**Comment by gzp-crey** [comment] 2019-12-04 17:08
And what about projects those are targeting actix-web 2.0 and require the Actor model ? Is there another tracking issue for this? For now the actix-web 2.0 without actor model is a huge braking change that'll hurt many projects.
If there is an alternative solution than please provide a migration guide.

**Comment by glademiller** [comment] 2019-12-04 22:48
Just to add my two cents for my use case I'm actually working on
alternative implementations to the few actors I am using in my projects
since most of them don't strictly require an actor model but I totally
agree at least in the near term this is driving my projects to leave actix
behind.

**Comment by HugoKempfer** [comment] 2019-12-19 15:47
Did https://github.com/actix/actix/pull/300 solves the issue?

**Comment by Luminoth** [comment] 2019-12-19 16:37
Seems like it should have. I'm wondering if that also means we can use async / await with actix now.
