### ISSUE TITLE
Upgrading actix from '0.10' to '0.11' breaks WebSocket Actors

### ISSUE THREAD

**Issue by dns2utf8** [actix/actix#500] opened 2021-05-19 11:06 UTC
I have this setup:

```rust
impl Actor for MyWs {
    type Context = WebsocketContext<Self>;
}
impl StreamHandler<Result<ws::Message, ws::ProtocolError>> for MyWs {
    fn handle(&mut self, msg: Result<ws::Message, ws::ProtocolError>, ctx: &mut Self::Context) {
        use ws::Message;
        // ...
    }
}
```

## Expected Behavior
It should still compile or there should be docs on how to upgrade.

## Current Behavior
```rust
error[E0277]: the trait bound `MyWs: actix::actor::Actor` is not satisfied
    --> src/game.rs:1420:76
     |
1420 |     fn handle(&mut self, msg: Result<ws::Message, ws::ProtocolError>, ctx: &mut Self::Context) {
     |                                                                            ^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `MyWs`
```

## Possible Solution
Going back to `actix = "0.10"`

## Steps to Reproduce (for bugs)

1. clone project https://gitlab.com/dns2utf8/multiplayer_snake/
2. update to `actix = "0.11"`
3. compile

## Context
I wanted to upgarde all my deps.

## Your Environment
Linux, the full project is here: https://gitlab.com/dns2utf8/multiplayer_snake/

* Rust Version (I.e, output of `rustc -V`): rustc 1.52.1 (9bc8c42bb 2021-05-09)
* Actix Version:
    ```toml
    actix-web = "3.3"
    actix-files = "0.5"
    actix = "0.10"
    actix-web-actors = "3.0"
    ```

**Comment by robjtede** [comment] 2021-05-19 11:33
Duplicate of https://github.com/actix/actix/issues/485

**Closed** 2021-05-19 11:33 UTC
