### ISSUE TITLE
Ring Test Not Send All Messages

### ISSUE THREAD

**Issue by plus7wist** [actix/actix#362] opened 2020-03-09 08:33 UTC
Dear professionals, I am at actix `v0.9.0`, I run ring test in `examples`, but it looks strange. If I use a big `<num-nodes>` and `num-times-message-around-ring>`, the code seems not send all messages.

```
>>> cargo ex ring 1000 1000
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `/tmp/cargo/debug/examples/ring 1000 1000`
Setting up nodes
Time taken: 0.015376 seconds
``` 

`Reached limit of xx (payload was xx)` not printed. And if I print a `hello` line in `hanele`, I can count the real number of times that `handle` run.

```
>>> cargo ex ring 1000 1000 | sort | uniq -c
   Compiling actix v0.9.0 (/home/plus7wist/develop/actix)
    Finished dev [unoptimized + debuginfo] target(s) in 1.63s
     Running `/tmp/cargo/debug/examples/ring 1000 1000`
     36 Hello
      1 Setting up nodes
      1 Time taken: 0.015231 seconds
```

If I checkout to `v0.8.0`. This test speed 8 seconds in my PC, and looks good (`Reached limit of xx (payload was xx)` is printed). So I find the first bad commit by `git bisect`:

```
aeb7bd15ea8793e5f00f17caefb01eb678136c2e is the first bad commit
commit aeb7bd15ea8793e5f00f17caefb01eb678136c2e
Author: Brandon McMillan <bcmcmill@users.noreply.github.com>
Date:   Sun Dec 15 10:16:17 2019 -0500

    Migrate to std::future, tokio 0.2 and actix-rt 1.0.0 (#300)
```

I am not good enough to fix this, I am sorry.

**Comment by Jonathas-Conceicao** [comment] 2020-03-10 01:08
@plus7wist could you confirm if this example happens to you on master too? I was not able to reproduce it on master but I was on the v0.9.0 tag. I believe this was already fixed on 5e8fdd0.

**Comment by plus7wist** [comment] 2020-03-11 02:22
Thx for help, It really fixed on my master. I should have checked it, I am so sorry.

So, after that commit, we should manually call a `System::run()`?

**Comment by Jonathas-Conceicao** [comment] 2020-03-11 03:21
It is one of the ways to run the system, but it's not the only one. For most common uses cases just using the `#[actix_rt::main]` or `#[actix_rt::test]` on the main or test should do the trick. We sometime avoid that for some of our integration tests when we want to do some processing _after_ the Actix's System has fully stopped.

**Comment by Jonathas-Conceicao** [comment] 2020-03-11 20:43
I'm closing the issue since the problem itself has been solved. Please feel free to ask on [gitter](https://gitter.im/actix/actix) if you have any general questions.

**Closed by Jonathas-Conceicao** 2020-03-11 20:43 UTC
